"use strict";

app.factory("TwitterFactory", function ($q, $http, firebaseURL){


    function getTweetIdExtremes (tweets) {
      let max = tweets[0].id,
          min = tweets[0].id;

      tweets.forEach( (tweet) => {
        if (tweet.id < min){
          minId = tweet.id;
        }

        if (tweet.id > max) {
          maxId = tweet.id;
        }
      });

      return {
        "minId": minId,
        "maxId": maxId 
      }
    }


  let data = { statuses: 
   [ { created_at: 'Sun May 29 23:32:17 +0000 2016',
       id: 737064046034190300,
       id_str: '737064046034190337',
       text: 'RT @iAmTerrace: Gucci Mane is dropping the hottest trap R&amp;B album of all time. https://t.co/h5YwXky3h5',
       truncated: false,
       entities: [Object],
       metadata: [Object],
       source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: [Object],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       retweeted_status: [Object],
       is_quote_status: false,
       retweet_count: 594,
       favorite_count: 0,
       favorited: false,
       retweeted: false,
       possibly_sensitive: false,
       lang: 'en' },
     { created_at: 'Sun May 29 23:32:15 +0000 2016',
       id: 737064037285040100,
       id_str: '737064037285040128',
       text: 'RT @DailyRapFacts: GUCCI MANE HAS BEEN RELEASED FROM PRISON https://t.co/cHJ6nU6PsO',
       truncated: false,
       entities: [Object],
       metadata: [Object],
       source: '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: [Object],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       retweeted_status: [Object],
       is_quote_status: false,
       retweet_count: 25895,
       favorite_count: 0,
       favorited: false,
       retweeted: false,
       possibly_sensitive: false,
       lang: 'en' },
     { created_at: 'Sun May 29 23:32:14 +0000 2016',
       id: 737064036462792700,
       id_str: '737064036462792704',
       text: 'RT @WeLoveRobDyrdek: Gucci Mane legendary https://t.co/bdZesKW8AZ',
       truncated: false,
       entities: [Object],
       metadata: [Object],
       source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: [Object],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       retweeted_status: [Object],
       is_quote_status: false,
       retweet_count: 332,
       favorite_count: 0,
       favorited: false,
       retweeted: false,
       possibly_sensitive: false,
       lang: 'it' },
     { created_at: 'Sun May 29 23:32:03 +0000 2016',
       id: 737063987985186800,
       id_str: '737063987985186817',
       text: 'RT @DailyLoud: Gucci Mane\'s new clothing line DELANTIC is coming soon https://t.co/7gVbEkJOqo',
       truncated: false,
       entities: [Object],
       metadata: [Object],
       source: '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: [Object],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       retweeted_status: [Object],
       is_quote_status: false,
       retweet_count: 628,
       favorite_count: 0,
       favorited: false,
       retweeted: false,
       possibly_sensitive: false,
       lang: 'en' },
     { created_at: 'Sun May 29 23:32:03 +0000 2016',
       id: 737063986437316600,
       id_str: '737063986437316608',
       text: 'RT @FunnyPicsDepot: "I\'m so I-C-Y all the girls love Gucci Mane &amp; I-C-Y" https://t.co/ICNRWkCgTD',
       truncated: false,
       entities: [Object],
       metadata: [Object],
       source: '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: [Object],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       retweeted_status: [Object],
       is_quote_status: false,
       retweet_count: 2753,
       favorite_count: 0,
       favorited: false,
       retweeted: false,
       possibly_sensitive: false,
       lang: 'en' },
     { created_at: 'Sun May 29 23:32:01 +0000 2016',
       id: 737063978879361000,
       id_str: '737063978879361024',
       text: 'I am broadcasting LIVE Gucci mane//Memorial Day weekend mix right now on #Mixlr. Tune in: https://t.co/7t65GRUEbI',
       truncated: false,
       entities: [Object],
       metadata: [Object],
       source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: [Object],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       is_quote_status: false,
       retweet_count: 0,
       favorite_count: 0,
       favorited: false,
       retweeted: false,
       possibly_sensitive: false,
       lang: 'en' },
     { created_at: 'Sun May 29 23:31:59 +0000 2016',
       id: 737063970784190500,
       id_str: '737063970784190464',
       text: 'Pretty sure I\'m gonna turn more purple than Gucci Mane\'s lips this summer 16.',
       truncated: false,
       entities: [Object],
       metadata: [Object],
       source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: [Object],
       geo: null,
       coordinates: null,
       place: [Object],
       contributors: null,
       is_quote_status: false,
       retweet_count: 0,
       favorite_count: 0,
       favorited: false,
       retweeted: false,
       lang: 'en' },
     { created_at: 'Sun May 29 23:31:45 +0000 2016',
       id: 737063912571441200,
       id_str: '737063912571441152',
       text: 'RT @GAFollowers: Gucci Mane about to snatch Atlanta back from these new rappers like.. https://t.co/xHLFXabMQf',
       truncated: false,
       entities: [Object],
       metadata: [Object],
       source: '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: [Object],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       retweeted_status: [Object],
       is_quote_status: false,
       retweet_count: 3023,
       favorite_count: 0,
       favorited: false,
       retweeted: false,
       possibly_sensitive: false,
       lang: 'en' },
     { created_at: 'Sun May 29 23:31:42 +0000 2016',
       id: 737063898826854400,
       id_str: '737063898826854402',
       text: 'RT @DailyRapFacts: GUCCI MANE HAS BEEN RELEASED FROM PRISON https://t.co/cHJ6nU6PsO',
       truncated: false,
       entities: [Object],
       metadata: [Object],
       source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: [Object],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       retweeted_status: [Object],
       is_quote_status: false,
       retweet_count: 25895,
       favorite_count: 0,
       favorited: false,
       retweeted: false,
       possibly_sensitive: false,
       lang: 'en' },
     { created_at: 'Sun May 29 23:31:41 +0000 2016',
       id: 737063894351380500,
       id_str: '737063894351380480',
       text: 'RT @daisydadon: GUCCI MANE FREE ... CARDI B GOT NEW TEETH .. God not playing no games this week',
       truncated: false,
       entities: [Object],
       metadata: [Object],
       source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: [Object],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       retweeted_status: [Object],
       is_quote_status: false,
       retweet_count: 3582,
       favorite_count: 0,
       favorited: false,
       retweeted: false,
       lang: 'en' } ],
  search_metadata: 
   { completed_in: 0.04,
     max_id: 737064046034190300,
     max_id_str: '737064046034190337',
     next_results: '?max_id=737063894351380479&q=gucci%20mane&count=10&include_entities=1',
     query: 'gucci+mane',
     refresh_url: '?since_id=737064046034190337&q=gucci%20mane&include_entities=1',
     count: 10,
     since_id: 0,
     since_id_str: '0' } }


  return {
    getRecentTweets(albumName, artistName, number ) {
      let params = `q=${artistName} OR ${albumName}&count=100&result_type=mixed`;

      let tweets = [];

      let callsMade = 0;


    return data.statuses;
    }
  }
});